### ISSUE TITLE
徒歩接続における時刻の計算

### ISSUE THREAD

**Issue by kazuhiro-takaya** [MaaSee/HARoSE#5]
routing.go 101(?)行目
`transArrivalTime := memo.Tau[r][fromStopId].ArrivalTime + int(v/query.MinuteSpeed*60)`
第2項がおかしい。変数vが徒歩での最小乗換時間[単位:秒]のはずなので。

**Comment by tesshy** [comment]
@takoyaki-3 これどう言う意味で第二項計算してんの？？

**Comment by takoyaki-3** [comment]
vを距離（メートル）だと思っていました

**Comment by takoyaki-3** [comment]
https://github.com/MaaSee/HARoSE/pull/11
で修正しました。
