### ISSUE TITLE
出力する経路の構成時にたどる親ポインタの修正

### ISSUE THREAD

**Issue by kazuhiro-takaya** [MaaSee/HARoSE#7]
- 徒歩乗換への対応
- 各ラウンド各停留所につき、到着時刻tauとともに、乗った便のtripID、乗車停留所のStopIDに加え、降車した停留所のStopIDも持っておく。
- server.goでの経路構成のロジックも修正する。

**Comment by tesshy** [comment]
@takoyaki-3 #10
