### ISSUE TITLE
検索結果の出力修正

### ISSUE THREAD

**Issue by kazuhiro-takaya** [MaaSee/HARoSE#8]
- 結果が得られない（"not found!"となる）場合に何らかのメッセージを出すべき？
- 複数の結果を出力したい：現状、最速＆最多乗換の1つだけが出力される。

**Comment by tesshy** [comment]
- https://github.com/MaaSee/HARoSE/blob/e49d04e20172239021c1121febac96c87db7c50d/exec/server.go#L54
HTTP 404を返すようにする

- 複数個返せるようにしよう・・・！
  - 基本的にArrayになる？

**Comment by kazuhiro-takaya** [comment]
#17

**Comment by kazuhiro-takaya** [comment]
#17 で修正、マージ完了
